[package]
name = "axum-server"
version = "0.1.0"
authors = ["Programatik <programatik29@gmail.com>"]
edition = "2018"
description = "High level server for axum."
license = "MIT"

[dependencies]
futures-util = "0.3"
tokio = { version = "1", features = ["rt", "net"] }
tokio-rustls = "0.22"
http = "0.2"
http-body = "0.4"
tower-service = "0.3.1"
tower-http = { version = "0.1", features = ["add-extension"] }
hyper = { version = "0.14", features = ["runtime", "server", "http1", "http2"] }
